"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class bruce_cmd_t(object):

    __slots__ = ["b_position", "rpy", "b_velocity"]

    __typenames__ = ["double", "double", "double"]

    __dimensions__ = [[3], [4], [3]]

    def __init__(self):
        self.b_position = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """
        self.rpy = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: double[4] """
        self.b_velocity = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """

    def encode(self):
        buf = BytesIO()
        buf.write(bruce_cmd_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3d', *self.b_position[:3]))
        buf.write(struct.pack('>4d', *self.rpy[:4]))
        buf.write(struct.pack('>3d', *self.b_velocity[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != bruce_cmd_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return bruce_cmd_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = bruce_cmd_t()
        self.b_position = struct.unpack('>3d', buf.read(24))
        self.rpy = struct.unpack('>4d', buf.read(32))
        self.b_velocity = struct.unpack('>3d', buf.read(24))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if bruce_cmd_t in parents: return 0
        tmphash = (0xe7aaedbe35e49ba7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if bruce_cmd_t._packed_fingerprint is None:
            bruce_cmd_t._packed_fingerprint = struct.pack(">Q", bruce_cmd_t._get_hash_recursive([]))
        return bruce_cmd_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", bruce_cmd_t._get_packed_fingerprint())[0]

