/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package bruce_cmd_lidar;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class bruce_cmd_lidar_t implements lcm.lcm.LCMEncodable
{
    public double com_z;

    /**
     * LCM Type: double[2]
     */
    public double com_velocity[];

    public double ang_vel_yaw;

 
    public bruce_cmd_lidar_t()
    {
        com_velocity = new double[2];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xa291f721bfccee99L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(bruce_cmd_lidar.bruce_cmd_lidar_t.class))
            return 0L;
 
        classes.add(bruce_cmd_lidar.bruce_cmd_lidar_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeDouble(this.com_z); 
 
        for (int a = 0; a < 2; a++) {
            outs.writeDouble(this.com_velocity[a]); 
        }
 
        outs.writeDouble(this.ang_vel_yaw); 
 
    }
 
    public bruce_cmd_lidar_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public bruce_cmd_lidar_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static bruce_cmd_lidar.bruce_cmd_lidar_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        bruce_cmd_lidar.bruce_cmd_lidar_t o = new bruce_cmd_lidar.bruce_cmd_lidar_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.com_z = ins.readDouble();
 
        this.com_velocity = new double[(int) 2];
        for (int a = 0; a < 2; a++) {
            this.com_velocity[a] = ins.readDouble();
        }
 
        this.ang_vel_yaw = ins.readDouble();
 
    }
 
    public bruce_cmd_lidar.bruce_cmd_lidar_t copy()
    {
        bruce_cmd_lidar.bruce_cmd_lidar_t outobj = new bruce_cmd_lidar.bruce_cmd_lidar_t();
        outobj.com_z = this.com_z;
 
        outobj.com_velocity = new double[(int) 2];
        System.arraycopy(this.com_velocity, 0, outobj.com_velocity, 0, 2); 
        outobj.ang_vel_yaw = this.ang_vel_yaw;
 
        return outobj;
    }
 
}

